### ISSUE TITLE
나의 프로필 조회 API 요청

### ISSUE THREAD

**Issue by jkim68888** [team-ppeople/pp-oas-swagger#5]
설정 페이지에서 나의 프로필 조회하려고 할때, 나의 userId를 알수없어서 유저 프로필 조회 API 요청이 불가합니다!

**Comment by sinbom** [comment]
> 설정 페이지에서 나의 프로필 조회하려고 할때, 나의 userId를 알수없어서 유저 프로필 조회 API 요청이 불가합니다!

제가 이 부분에 대해서 말씀을 안드렸네요!
서버에서 JWT 토큰의 claims에 userId를 포함시켜서 서명하고 발급할 예정입니다.

**Comment by jkim68888** [comment]
아하 넵! 알겠습니다! 
그럼 해당 이슈는 닫겠습니다~
